### ISSUE TITLE
attemping to build this lib (within holochain) for ios target fails

### ISSUE THREAD

**Issue by Connoropolous** [neonphog/one_err#3]
I realize it's not a supported platform, but if I wanted to contribute a fix to this issue in this repo, what might I do?

<img width="829" alt="Screenshot 2022-12-11 at 8 10 28 AM" src="https://user-images.githubusercontent.com/1409121/206914990-33bd8333-8be8-4bdc-9ec5-ebc2aa2239b4.png">

**Comment by neonphog** [comment]
@Connoropolous - take a look at this PR: https://github.com/neonphog/one_err/pull/2

This looks very similar.

**Comment by Connoropolous** [comment]
oo, perfect! thanks!
